"""从 PDF 坐标重建财报表格，按列期间 + 行标签提取数值（非逐公司正则）。"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from typing import Dict, List, Optional, Tuple

import pdfplumber

from backend.global_schema.models import GlobalField, StatementType, ValueScale
from backend.global_schema.registry import GLOBAL_FIELDS_V1
from backend.markets.us.period_parser import StatementPeriod, parse_statement_periods
from backend.pipeline.text_grid_extractor import extract_text_grid_from_page

# 全球通用财报行标签（Schema 级，非公司定制）
FIELD_LABEL_ALIASES: Dict[str, List[str]] = {
    "revenue": [
        "revenue",
        "revenues",
        "total revenues",
        "net sales",
        "total net sales",
        "total net revenues",
        "total revenue",
        "turnover",
        "operating revenue",
        "ventes",
        "chiffre d'affaires",
        "chiffre d affaires",
        "produits",
        "营业收入",
        "营业总收入",
        "收入",
    ],
    "gross_profit": ["gross profit", "gross margin", "毛利", "毛利润"],
    "operating_income": [
        "operating income",
        "income from operations",
        "operating profit",
        "operating income (loss)",
        "loss from operations",
        "earnings from operations",
        "résultat opérationnel",
        "经营溢利",
        "经营利润",
        "营业利润",
    ],
    "net_income": [
        "net income",
        "net earnings",
        "net income (loss)",
        "net earnings (loss)",
        "profit for the year",
        "profit attributable to equity holders",
        "profit attributable to owners",
        "profit attributable to shareholders",
        "résultat net",
        "résultat net de l'ensemble consolidé",
        "résultat net, part du groupe",
        "part attribuable aux actionnaires",
        "本公司权益持有人应占溢利",
        "本公司拥有人应占溢利",
        "股东应占溢利",
        "净利润",
    ],
    "eps_basic": [
        "basic earnings per share",
        "basic net income per share",
        "basic eps",
        "basic and diluted earnings per share",
        "net income per share: basic",
        "net income per share basic",
        "earnings per share basic",
        "基本每股盈利",
        "每股基本盈利",
        "– basic",
        "- basic",
        "basic",
    ],
    "total_assets": [
        "total assets",
        "total actif",
        "total de l'actif",
        "total de l actif",
        "总资产",
        "资产总值",
        "资产总额",
    ],
    "total_liabilities": [
        "total liabilities",
        "total des passifs",
        "passif",
        "总负债",
        "负债总额",
        "负债总值",
    ],
    "total_equity": [
        "total stockholders' equity",
        "total shareholders' equity",
        "total equity",
        "total equity attributable to equity shareholders of the bank",
        "equity attributable to owners of the parent",
        "equity attributable to equity holders of the parent",
        "total des capitaux propres",
        "capitaux propres",
        "股东权益",
        "权益总额",
        "权益总值",
        "本公司权益持有人应占权益",
        "本公司拥有人应占权益",
    ],
    "cash": [
        "cash and cash equivalents",
        "cash and deposits with central banks",
        "cash and amounts due from banks",
        "现金及现金等价物",
        "现金及等同现金项目",
    ],
    "cfo": [
        "net cash provided by operating activities",
        "net cash from operating activities",
        "net cash from operations",
        "net cash provided by (used in) operating activities",
        "cash generated by operating activities",
        "cash flows from operating activities",
        "经营活动所得现金流量净额",
        "经营活动产生的现金流量净额",
        "经营业务所得现金净额",
    ],
    "cfi": [
        "net cash used in investing activities",
        "net cash provided by investing activities",
        "net cash provided by (used in) investing activities",
        "cash flows from investing activities",
        "投资活动所得现金流量净额",
        "投资活动产生的现金流量净额",
    ],
    "cff": [
        "net cash used in financing activities",
        "net cash provided by financing activities",
        "net cash used in (provided by) financing activities",
        "cash flows from financing activities",
        "融资活动所得现金流量净额",
        "筹资活动产生的现金流量净额",
    ],
    "capex": [
        "purchases of property and equipment",
        "purchase of property, plant and equipment",
        "purchase of property, equipment and software",
        "capital expenditures",
        "purchase of property",
        "购置物业",
        "购建固定资产",
        "资本开支",
    ],
}

PERIOD_DATE_HEADER_RE = re.compile(
    r"(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|"
    r"Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)"
    r"\s+(\d{1,2}),?\s+(20\d{2})",
    re.IGNORECASE,
)

_EU_THOUSANDS_AMOUNT_RE = re.compile(
    r"\(?\s*-?\d{1,3}(?:[ \u00a0\u202f\u2009]\d{3})+(?:\.\d+)?\s*\)?"
)

EQUITY_LIABILITIES_COMBINED_RE = re.compile(
    r"equity.{0,40}\s+and\s+liabilit|"
    r"liabilit(?:ies|y).{0,60}\s+and\s+(?:shareholders?.?|stockholders?.?|equity)\b|"
    r"and\s+(?:stockholders|shareholders|equity)\b|"
    r"passif.{0,40}\s+et\s+.{0,40}capitaux propres|"
    r"capitaux propres.{0,40}\s+et\s+.{0,40}passif",
    re.IGNORECASE,
)
LIABILITIES_COMBINED_LINE_RE = EQUITY_LIABILITIES_COMBINED_RE
EQUITY_COMBINED_LINE_RE = re.compile(
    r"(?:equity|stockholders?.? equity|shareholders?.? equity)\s+and\s+liabilit|"
    r"liabilit(?:ies|y).{0,60}\s+and\s+(?:shareholders?.?|stockholders?.?)\s+equity|"
    r"liabilit(?:ies|y).{0,60}\s+and\s+equity\b",
    re.IGNORECASE,
)
SEGMENT_TOTAL_REVENUE_RE = re.compile(
    r"^total\s+(?:automotive|energy|services|segment|product|geographic|regional|"
    r"cloud|compute|data\s*center|advertising|mobile|storage|networking|graphics)\s+revenues?$",
    re.IGNORECASE,
)
COMPANY_TOTAL_REVENUE_RE = re.compile(
    r"^total(?:\s+net)?\s+(?:revenues?|sales)$",
    re.IGNORECASE,
)

STMT_FIELDS = {
    StatementType.INCOME: "income",
    StatementType.BALANCE: "balance",
    StatementType.CASHFLOW: "cashflow",
}


@dataclass
class StatementGrid:
    statement_type: str
    period_ends: List[str]
    rows: List[Tuple[str, List[str]]] = field(default_factory=list)


def _cell_has_amount(text: str) -> bool:
    return bool(re.search(r"\d", str(text)))


def _cell_looks_like_amount(text: str) -> bool:
    """区分行标签区误并入的数值列与脚注（如 2(z)）。"""
    t = str(text).strip()
    if not t:
        return False
    if _EU_THOUSANDS_AMOUNT_RE.fullmatch(t):
        return True
    if re.search(r"\d{1,3}(?:,\d{3})+", t):
        return True
    digits_only = re.sub(r"[^\d]", "", t)
    if digits_only and re.fullmatch(r"[\(\)\$\s\-]*[\d,]+(?:\.\d+)?[\(\)\$\s\-]*", t):
        return True
    return False


def _normalize_numeric_cell_text(text: str) -> str:
    """PDF 渲染导致数字字符成对重复（如 1177,,334455 → 17,345）。"""
    cleaned = _dedupe_stuttered_text(str(text).strip())
    cleaned = re.sub(r"(?<=\d)[ \u00a0\u202f\u2009]+(?=\d)", "", cleaned)
    if not re.search(r"\d", cleaned):
        return cleaned

    digits = re.sub(r"[^\d]", "", cleaned)
    if len(digits) >= 8:
        dup_adjacent = sum(1 for i in range(len(digits) - 1) if digits[i] == digits[i + 1])
        if dup_adjacent >= len(digits) * 0.35:
            deduped = []
            i = 0
            while i < len(digits):
                deduped.append(digits[i])
                if i + 1 < len(digits) and digits[i] == digits[i + 1]:
                    i += 2
                else:
                    i += 1
            return "".join(deduped)
    return cleaned


def _sanitize_cell_numeric_text(text: str) -> str:
    """修正 PDF 网格常见 OCR：花括号负号、字母 I 误识为 1。"""
    cleaned = str(text).strip().replace("{", "(").replace("}", ")")
    paren = re.search(r"\(\s*([^)]+)\)", cleaned)
    if paren:
        inner = paren.group(1).replace("I", "1").replace("l", "1")
        inner = re.sub(r"[\s,]", "", inner)
        if inner.isdigit():
            cleaned = cleaned[: paren.start()] + f"({inner})" + cleaned[paren.end() :]
    return cleaned


def _parse_cell_amount(text: str, per_share: bool = False) -> Optional[float]:
    if not text or not str(text).strip():
        return None
    raw_input = _sanitize_cell_numeric_text(_dedupe_stuttered_text(str(text).strip()))

    paren = re.search(r"\(\s*([\d,]+(?:\.\d+)?)\s*\)", raw_input)
    if paren:
        inner = _normalize_numeric_cell_text(paren.group(1))
        val = float(inner.replace(",", ""))
        return -val

    raw = _normalize_numeric_cell_text(raw_input)

    paren = re.search(r"\(\s*([\d,]+(?:\.\d+)?)\s*\)", raw)
    if paren:
        return -float(paren.group(1).replace(",", ""))

    if per_share:
        m = re.search(r"\$?\s*-?([\d,]+\.[\d]+)", raw)
        if not m:
            return None
        val = float(m.group(1).replace(",", ""))
        if raw.strip().startswith("-") or raw.strip().startswith("(-") or "$ -" in raw:
            val = -val
        return val

    cleaned = raw.replace("$", "").replace(",", "").strip()
    m = re.search(r"-?[\d]+(?:\.[\d]+)?", cleaned)
    if not m:
        return None
    val = float(m.group(0))
    if not per_share and abs(val) < 1000:
        return None
    return val


def _dedupe_stuttered_text(text: str) -> str:
    """PDF 渲染偶发字符重复（如 NNeett rreevveennuuee）。"""
    letters = [c for c in text if c.isalpha()]
    if len(letters) < 4:
        return text
    doubled = sum(
        1
        for i in range(len(text) - 1)
        if text[i].isalpha() and text[i].lower() == text[i + 1].lower()
    )
    if doubled >= len(letters) * 0.3:
        return re.sub(r"(.)\1", r"\1", text)
    return text


def _normalize_label(text: str) -> str:
    text = _dedupe_stuttered_text(str(text).replace("\t", " "))
    text = re.sub(r"/\s*\(", " (", text)
    text = text.lower().strip()
    # pdfplumber 常丢失词间空格（如 NetincomeattributabletoBaidu,Inc.）
    text = re.sub(
        r"(netincome|netloss|operatingincome|comprehensiveincome)(?=attributable)",
        r"\1 ",
        text,
    )
    text = re.sub(r"attributableto(the)?", r"attributable to \1", text)
    text = re.sub(r"less:net", "less: net ", text)
    return re.sub(r"\s+", " ", text).strip()


_CURRENCY_HEADER_RE = re.compile(r"\b(RMB|CNY|USD|US\$|HKD|HK\$|EUR|GBP)\b", re.I)


def _normalize_currency_token(token: str) -> str:
    t = token.upper().replace("$", "")
    if t in {"RMB", "CNY"}:
        return "CNY"
    if t in {"US", "USD"}:
        return "USD"
    if t in {"HK", "HKD"}:
        return "HKD"
    return t


def _column_currency_map(df, page_text: str) -> Dict[int, str]:
    """扫描表头行，推断各列币种（20-F 常见 RMB RMB RMB US$）。"""
    mapping: Dict[int, str] = {}
    scan_rows = min(8, len(df))
    for row_idx in range(scan_rows):
        for col_idx in range(len(df.columns)):
            cell = str(df.iloc[row_idx, col_idx]).strip()
            m = _CURRENCY_HEADER_RE.search(cell)
            if m:
                mapping[col_idx] = _normalize_currency_token(m.group(1))
    if mapping:
        return mapping

    head = page_text[:2500].upper()
    default = "CNY" if re.search(r"\bRMB\b|CNY|人民币", head) else "USD"
    for col_idx in range(len(df.columns)):
        if col_idx not in mapping:
            mapping[col_idx] = default
    return mapping


def _preferred_currency_from_text(page_text: str) -> str:
    head = page_text[:2500].upper()
    if re.search(r"\bRMB\b|CNY|人民币", head):
        return "CNY"
    if re.search(r"\bHKD\b|港元|港幣", head):
        return "HKD"
    if re.search(r"\bUSD\b|US\$", head):
        return "USD"
    return "CNY"


def _expand_statement_start(pages_text: List[str], start_page: int, statement_type: str) -> int:
    """若定位在 (Continued) 页，回溯到该报表首页（如 JD balance 265–267）。"""
    from backend.markets.us.statement_locator import normalize_page_text

    start = start_page
    title_patterns = {
        "income": [
            r"consolidated\s+statements?\s+of\s+operations",
            r"statements?\s+of\s+operations",
            r"statements?\s+of\s+comprehensive\s+income",
            r"consolidated\s+statements?\s+of\s+comprehensive\s+income",
            r"consolidated\s+statements?\s+of\s+comprehensive\s+loss",
            r"statements?\s+of\s+comprehensive\s+loss",
            r"consolidated\s+income\s+statements?",
        ],
        "balance": [
            r"consolidated\s+balance\s+sheets?",
            r"statements?\s+of\s+financial\s+position",
        ],
        "cashflow": [
            r"consolidated\s+statements?\s+of\s+cash\s+flows?",
            r"statements?\s+of\s+cash\s+flows?",
        ],
    }.get(statement_type, [])

    while start > 0:
        head = normalize_page_text(pages_text[start])[:600].lower()
        if re.search(r"\(continued\)", head):
            start -= 1
            continue
        break

    while start > 0:
        prev = normalize_page_text(pages_text[start - 1])[:600].lower()
        if not any(re.search(pat, prev, re.I) for pat in title_patterns):
            break
        if re.search(r"\(continued\)", prev) or not re.search(r"\(continued\)", normalize_page_text(pages_text[start])[:600].lower()):
            start -= 1
            if not re.search(r"\(continued\)", prev):
                break
        else:
            break
    return start


def _statement_page_span(pages_text: List[str], start_page: int, statement_type: str) -> Tuple[int, int]:
    from backend.markets.us.statement_text import NEXT_STATEMENT_MARKERS

    start = _expand_statement_start(pages_text, start_page, statement_type)
    end = start + 1
    max_extra = 6 if statement_type == "cashflow" else 4
    markers = NEXT_STATEMENT_MARKERS.get(statement_type, [])
    for offset in range(1, max_extra + 1):
        idx = start + offset
        if idx >= len(pages_text):
            break
        head = pages_text[idx][:400].lower()
        if any(re.search(pat, head) for pat in markers):
            break
        end = idx + 1
    return start, end


def _page_belongs_to_statement(page_text: str, statement_type: str) -> bool:
    from backend.markets.us.statement_locator import _validate_statement_page, normalize_page_text

    head = normalize_page_text(page_text)[:500].lower()
    body = normalize_page_text(page_text)[:3000].lower()
    if _validate_statement_page(page_text, statement_type):
        if re.search(r"\(continued\)", head):
            return True
        if statement_type == "income" and re.search(r"comprehensive\s+income", head):
            if not re.search(
                r"\b(?:revenues?|net sales|cost of revenue|gross profit|total operating income)\b",
                body,
            ):
                return False
        return True
    if re.search(r"\(continued\)", head):
        return True
    if statement_type == "cashflow" and re.search(
        r"consolidated statements of cash flows|statements of cash flows",
        head,
        re.I,
    ) and re.search(
        r"cash flows from (?:investing|financing) activities|"
        r"net cash (?:provided|used|generated)",
        head,
        re.I,
    ):
        return True
    return False


def _resolve_split_row_label(label: str, pending_label: str, section_prefix: str) -> Tuple[str, str, str]:
    """合并 PDF 折行标签（如 'and intangible assets'、'Basic' EPS 行）。"""
    norm = label.strip().lower()
    updated_pending = pending_label
    updated_section = section_prefix

    if re.match(r"^and\s+", label, re.I):
        if pending_label:
            label = f"{pending_label} {label}".strip()
        elif re.search(r"intangible assets", label, re.I):
            label = f"Purchase of property, equipment and software {label}".strip()
        updated_pending = ""

    if norm in ("basic", "diluted") and section_prefix:
        label = f"{section_prefix} {label}".strip()
        updated_section = ""

    return label, updated_pending, updated_section


def _row_label_score(label: str, field: GlobalField) -> float:
    norm = _normalize_label(label)
    if not norm:
        return 0.0
    if re.search(r"\d{1,3},\d{3}", norm):
        return 0.0

    aliases = FIELD_LABEL_ALIASES.get(field.field_id, [])
    aliases = aliases + [_normalize_label(field.label_en)]

    if field.field_id in {"total_liabilities", "total_equity"} and EQUITY_LIABILITIES_COMBINED_RE.search(
        norm
    ):
        return 0.0
    if field.field_id == "total_liabilities" and re.search(r"\bequity\b", norm) and not re.search(
        r"liabilit", norm
    ):
        return 0.0
    if field.field_id == "total_equity" and re.search(r"\bliabilit", norm) and not re.search(
        r"equity", norm
    ):
        return 0.0

    best = 0.0
    for alias in aliases:
        if norm == alias:
            if field.field_id == "total_equity" and re.fullmatch(
                r"total (?:stockholders?|shareholders?).? equity", norm
            ):
                return 1.0
            if field.field_id == "total_equity" and re.fullmatch(r"total equity", norm):
                return 0.85
            return 1.0
        if alias in norm or norm in alias:
            best = max(best, 0.92)
        best = max(best, SequenceMatcher(None, norm, alias).ratio())

    # 排除合并合计行（Total liabilities and stockholders' equity / and Equity）
    if field.field_id == "total_liabilities" and LIABILITIES_COMBINED_LINE_RE.search(norm):
        return 0.0
    if field.field_id == "total_liabilities" and re.search(
        r"uncertain tax|income tax|deferred tax|pension|lease liabilit|contract liabilit|"
        r"accrued and other|provisions?",
        norm,
    ) and not re.fullmatch(r"total liabilities", norm):
        return 0.0
    if field.field_id == "total_liabilities" and re.search(r"\bown funds\b", norm):
        return 0.0
    if field.field_id == "total_liabilities" and re.search(r"\bcurrent\b", norm) and not re.fullmatch(
        r"total liabilities", norm
    ):
        return 0.0
    if field.field_id == "total_assets" and re.search(r"\bus gaap\b", norm):
        return min(best, 0.45)
    if field.field_id == "total_assets" and re.search(r"\b(?:eu[- ]?ifrs|ifrs)\b", norm):
        return 1.0
    if field.field_id == "total_equity" and re.search(r"\btotal assets\b", norm):
        return 0.0
    if field.field_id == "total_equity" and EQUITY_COMBINED_LINE_RE.search(norm):
        return 0.0
    if field.field_id.startswith("total_") and "total" not in norm:
        return 0.0
    if field.field_id == "revenue" and "cost" in norm:
        return 0.0
    if field.field_id == "revenue" and SEGMENT_TOTAL_REVENUE_RE.search(norm):
        return min(best, 0.72)
    if field.field_id == "revenue" and COMPANY_TOTAL_REVENUE_RE.search(norm):
        return 1.0
    if field.field_id == "net_income" and re.fullmatch(r"consolidated net income(?: \(loss\))?", norm):
        return min(best, 0.80)
    if field.field_id == "net_income" and re.search(
        r"consolidated net income attributable to (?!non[- ]?controlling)",
        norm,
    ):
        return 1.0
    if field.field_id == "net_income" and re.search(r"^net income(?:/(?:expense))? from\b", norm):
        return 0.0
    if field.field_id == "net_income" and re.search(r"profit for the year", norm):
        return 1.0
    if field.field_id == "net_income" and re.search(
        r"r[eé]sultat net(?: de l.?ensemble consolid[eé])?", norm
    ):
        return 1.0
    if field.field_id == "net_income" and "per share" in norm:
        return 0.0
    if field.field_id == "net_income" and "discontinued" in norm:
        return 0.0
    if field.field_id == "net_income" and "continuing" in norm:
        return 1.0
    if field.field_id == "net_income" and re.search(r"non[- ]?controlling", norm):
        return 0.0
    if field.field_id == "net_income" and re.search(
        r"profit attributable to shareholders of (?:the )?company", norm
    ) and "ordinary" not in norm:
        return 1.0
    if field.field_id == "net_income" and "ordinary shareholders" in norm:
        return min(best, 0.88)
    if field.field_id == "net_income" and re.fullmatch(
        r"net income(?: \(loss\))?", norm.strip()
    ):
        return min(best, 0.85)
    if field.field_id == "net_income" and re.fullmatch(r"net (?:income|loss)(?: \(loss\))?", norm.strip()):
        return 0.9
    if field.field_id == "net_income" and re.fullmatch(r"netincome(?:\(loss\))?", norm):
        return min(best, 0.85)
    if field.field_id == "net_income" and re.search(r"attributable to", norm) and not re.search(
        r"non[- ]?controlling", norm
    ):
        return 1.0
    if field.field_id == "net_income" and re.search(
        r"net income attributable to .+",
        norm,
    ) and not re.search(r"non[- ]?controlling", norm):
        return 1.0
    if field.field_id == "net_income" and re.search(
        r"(?:group\s+)?holding\s+limited$",
        norm,
    ) and not re.search(r"non[- ]?controlling|shareholders? of", norm):
        return 0.96
    if field.field_id == "net_income" and re.search(
        r"^(?:ordinary\s+)?shareholders of\b",
        norm,
    ):
        return min(best, 0.72)
    if field.field_id == "net_income" and norm in ("shareholders", "ordinary shareholders"):
        return min(best, 0.55)
    if field.field_id == "net_income" and "common shareholders" in norm:
        return 1.0
    if field.field_id == "operating_income" and "non-operating" in norm:
        return 0.0
    if field.field_id == "operating_income" and re.search(r"^other operating income", norm):
        return 0.0
    if field.field_id == "operating_income" and re.search(
        r"(?:income|loss) from operations", norm
    ):
        return min(1.0, best + 0.1)
    if field.field_id == "eps_basic":
        if re.fullmatch(r"(?:basic|–\s*basic|-\s*basic)", norm):
            return 0.88
        if "per share" not in norm and not re.search(r"基本每股|每股基本", norm):
            return 0.0
    cashflow_activity = {
        "cfo": "operating",
        "cfi": "investing",
        "cff": "financing",
    }.get(field.field_id)
    if cashflow_activity:
        if cashflow_activity not in norm:
            return 0.0
        for other in ("operating", "investing", "financing"):
            if other != cashflow_activity and other in norm:
                return 0.0
        if re.search(r"^cash flows from (?:operating|investing|financing)", norm):
            return 0.0
        if re.search(r"^net cash", norm):
            return min(1.0, best + 0.08)
    if field.field_id == "revenue" and "total" in norm:
        return min(1.0, best + 0.08)
    if field.field_id == "total_equity":
        if "mezzanine" in norm:
            return 0.0
        if re.search(r"investments? in equity", norm):
            return 0.0
        if re.search(r"non[- ]?controlling", norm):
            return 0.0
        # 20-F/ADR：母公司权益行对齐 XBRL StockholdersEquity（非含 NCI 的合计行）
        if re.search(
            r"(?:inc\.?|ltd\.?|corp\.?|company|parent).{0,40}shareholders?.? equity|"
            r"shareholders?.? equity.{0,40}(?:inc\.?|ltd\.?|company)|"
            r"equity attributable to (?:the )?(?:company|parent|owners|shareholders)",
            norm,
        ):
            return 1.0
        if re.fullmatch(r"total shareholders?.? equity", norm):
            return min(best, 0.90)
    if field.field_id == "total_assets" and "liabilit" in norm:
        return 0.0
    if field.field_id == "total_equity" and re.search(r"\btotal assets\b", norm):
        return 0.0
    if field.field_id == "total_liabilities" and re.search(r"\btotal assets\b", norm):
        return 0.0
    if field.field_id == "eps_basic":
        if "diluted" in norm:
            return 0.0
        if re.search(r"shares outstanding|weighted.average shares|million shares", norm):
            return 0.0
        if re.fullmatch(r"(?:basic|–\s*basic|-\s*basic)", norm):
            return 0.88
        if re.search(r"earnings per share", norm) and re.search(r"\bbasic\b", norm):
            return 1.0
        if re.search(r"net income.*per share.*basic|basic.*net income per share", norm):
            return 1.0
        if re.search(r"基本每股|每股基本", norm):
            return 0.95
        if norm == "basic" and best < 0.5:
            return 0.75
    if field.field_id == "capex":
        if re.search(r"land use rights|repurchase|time deposits|wealth management", norm):
            return 0.0
        if re.search(r"property.{0,40}equipment|equipment.{0,40}software|intangible assets", norm):
            return max(best, 0.95)
    return best


def build_fiscal_calendar(pages_text: List[str], statement_pages: Dict[str, int]) -> Dict[int, str]:
    """从各报表页眉汇总 fiscal year → period_end（处理损益表仅标年份的情况）。"""
    calendar: Dict[int, str] = {}
    specificity: Dict[int, int] = {}

    def _score(label: str) -> int:
        if PERIOD_DATE_HEADER_RE.search(label):
            return 3
        if re.fullmatch(r"(20\d{2})", label.strip()):
            return 1
        if re.search(r"(20\d{2})", label):
            return 2
        return 0

    for page_num in statement_pages.values():
        if page_num >= len(pages_text):
            continue
        for period in parse_statement_periods(pages_text[page_num], max_periods=5):
            rank = _score(period.label)
            prev = specificity.get(period.year, -1)
            if rank > prev:
                calendar[period.year] = period.period_end
                specificity[period.year] = rank
    return calendar


def _period_end_from_header_text(
    text: str,
    page_text: str,
    fiscal_calendar: Optional[Dict[int, str]] = None,
) -> Optional[str]:
    from backend.markets.us.period_parser import _to_iso

    header = _dedupe_stuttered_text(str(text).strip())
    if not header:
        return None

    dm = PERIOD_DATE_HEADER_RE.search(header)
    if dm:
        month, day, year = dm.group(1), int(dm.group(2)), int(dm.group(3))
        return _to_iso(month, day, year)

    ym = re.fullmatch(r"(20\d{2})", header)
    if ym:
        year = int(ym.group(1))
        if fiscal_calendar and year in fiscal_calendar:
            return fiscal_calendar[year]
        parsed = parse_statement_periods(page_text, max_periods=4)
        for period in parsed:
            if period.year == year:
                return period.period_end
        if fiscal_calendar:
            for pe in fiscal_calendar.values():
                if pe.startswith(str(year)):
                    return pe
        return f"{year}-12-31"

    years = re.findall(r"\b(20\d{2})\b", header)
    if len(years) == 1:
        return _period_end_from_header_text(years[0], page_text, fiscal_calendar)
    return None


def _amount_density_by_column(df) -> Dict[int, int]:
    counts: Dict[int, int] = {}
    for col_idx in range(len(df.columns)):
        counts[col_idx] = sum(
            1
            for _, row in df.iterrows()
            if _cell_looks_like_amount(str(row.iloc[col_idx]))
        )
    return counts


def _column_header_is_note_column(df, col_idx: int) -> bool:
    header = str(df.columns[col_idx]).strip().lower()
    if re.search(r"\bnote\b", header):
        return True
    sample = " ".join(
        str(df.iloc[i, col_idx]).strip()
        for i in range(min(8, len(df)))
        if str(df.iloc[i, col_idx]).strip()
    ).lower()
    return sample == "note" or sample.startswith("note ")


def _resolve_amount_columns(
    df,
    header_cols: List[Tuple[int, str]],
    preferred_currency: Optional[str] = None,
    page_text: str = "",
) -> Tuple[List[int], List[str]]:
    """按列位置顺序匹配期间头与含数值的数据列。"""
    header_cols = sorted(header_cols, key=lambda x: x[0])
    period_ends = [p for _, p in header_cols]
    density = _amount_density_by_column(df)
    min_density = max(2, len(df) // 12)
    amount_cols = [c for c in sorted(density) if c > 0 and density[c] >= min_density]

    col_currency = _column_currency_map(df, page_text) if preferred_currency else {}

    def _currency_ok(col_idx: int) -> bool:
        if not preferred_currency or preferred_currency == "USD":
            return True
        return col_currency.get(col_idx, preferred_currency) == preferred_currency

    header_indices = [h for h, _ in header_cols]
    aligned_cols: List[int] = []
    for header_idx in header_indices:
        best_col = header_idx
        if _column_header_is_note_column(df, header_idx):
            for c in range(header_idx + 1, len(df.columns)):
                if density.get(c, 0) >= min_density:
                    best_col = c
                    break
        elif (
            header_idx + 1 < len(df.columns)
            and density.get(header_idx, 0) == 0
            and density.get(header_idx + 1, 0) > 0
        ):
            best_col = header_idx + 1
        aligned_cols.append(best_col)

    if len(aligned_cols) == len(period_ends):
        relaxed_density = max(1, min_density // 2)
        if all(density.get(c, 0) >= relaxed_density for c in aligned_cols):
            if all(_currency_ok(c) for c in aligned_cols):
                return aligned_cols, period_ends

    if preferred_currency and preferred_currency != "USD":
        filtered = [c for c in amount_cols if _currency_ok(c)]
        if len(filtered) >= len(period_ends):
            amount_cols = filtered

    if len(amount_cols) >= len(period_ends):
        data_cols = amount_cols[-len(period_ends) :]
        return data_cols, period_ends

    used: set[int] = set()
    data_cols: List[int] = []
    for header_idx, period_end in zip([h for h, _ in header_cols], period_ends):
        best_col = header_idx
        if _column_header_is_note_column(df, header_idx):
            for c in range(header_idx + 1, len(df.columns)):
                if c not in used and density.get(c, 0) > 0:
                    best_col = c
                    break
        elif (
            header_idx + 1 < len(df.columns)
            and density.get(header_idx, 0) == 0
            and density.get(header_idx + 1, 0) > 0
        ):
            best_col = header_idx + 1
        if best_col in used:
            for c in range(header_idx, len(df.columns)):
                if c not in used and density.get(c, 0) > 0:
                    best_col = c
                    break
        used.add(best_col)
        data_cols.append(best_col)
    return data_cols, period_ends


def _dedupe_period_currency_columns(
    data_cols: List[int],
    period_ends: List[str],
    df,
    page_text: str,
    preferred_currency: Optional[str],
) -> Tuple[List[int], List[str]]:
    """同一期间多列（如 RMB + USD）时保留 preferred_currency 列。"""
    if not preferred_currency or len(data_cols) != len(period_ends):
        return data_cols, period_ends
    col_currency = _column_currency_map(df, page_text)
    kept_cols: List[int] = []
    kept_periods: List[str] = []
    period_to_idx: Dict[str, int] = {}
    for col, pe in zip(data_cols, period_ends):
        cur = col_currency.get(col, preferred_currency)
        if pe not in period_to_idx:
            period_to_idx[pe] = len(kept_cols)
            kept_cols.append(col)
            kept_periods.append(pe)
            continue
        idx = period_to_idx[pe]
        prev_col = kept_cols[idx]
        prev_cur = col_currency.get(prev_col, preferred_currency)
        if cur == preferred_currency and prev_cur != preferred_currency:
            kept_cols[idx] = col
        elif prev_cur != preferred_currency and cur == preferred_currency:
            kept_cols[idx] = col
    return kept_cols, kept_periods


def _detect_period_columns(
    df,
    page_text: str,
    fiscal_calendar: Optional[Dict[int, str]] = None,
    preferred_currency: Optional[str] = None,
) -> Tuple[List[int], List[str]]:
    """返回 (数据列索引, 各列 period_end)。列头可能在 df.columns 或前几行单元格。"""
    col_periods: List[Tuple[int, str]] = []

    for col_idx, col_name in enumerate(df.columns):
        period_end = _period_end_from_header_text(str(col_name), page_text, fiscal_calendar)
        if period_end:
            col_periods.append((col_idx, period_end))

    if len(col_periods) < 2:
        for _, row in df.head(6).iterrows():
            row_cols: List[Tuple[int, str]] = []
            for col_idx, val in enumerate(row.values):
                period_end = _period_end_from_header_text(str(val), page_text, fiscal_calendar)
                if period_end:
                    row_cols.append((col_idx, period_end))
            if len(row_cols) >= 2:
                col_periods = row_cols
                break

    if len(col_periods) < 2:
        return [], []

    col_periods.sort(key=lambda x: x[0])
    data_cols, period_ends = _resolve_amount_columns(df, col_periods, preferred_currency, page_text)
    return _dedupe_period_currency_columns(
        data_cols, period_ends, df, page_text, preferred_currency
    )


def _detect_year_header(df) -> Tuple[List[int], List[int]]:
    """返回 (数据列索引, 对应年份) — 兼容旧调用。"""
    data_cols, period_ends = _detect_period_columns(df, "")
    if not data_cols:
        return [], []
    years = [int(pe[:4]) for pe in period_ends]
    return data_cols, years


def _period_ends_for_years(page_text: str, years: List[int], statement_type: str) -> List[str]:
    parsed = parse_statement_periods(page_text, max_periods=len(years) + 2)
    by_year = {p.year: p.period_end for p in parsed}
    ends: List[str] = []
    for year in years:
        if year in by_year:
            ends.append(by_year[year])
        else:
            ends.append(f"{year}-12-31")
    return ends


def _column_looks_like_period_header(df, col_idx: int) -> bool:
    """列是否主要为年份/币种表头（区别于含脚注年份的行标签列）。"""
    cells = [
        str(df.iloc[i, col_idx]).strip()
        for i in range(min(8, len(df)))
        if str(df.iloc[i, col_idx]).strip()
    ]
    if not cells:
        return False
    header_like = 0
    for cell in cells:
        if re.fullmatch(r"(?:20\d{2})(?:\s+20\d{2})*", cell.strip()):
            header_like += 1
        elif re.fullmatch(
            r"(?:RMB|USD|US\$|CNY|HKD)(?:\s+(?:RMB|USD|US\$|CNY|HKD))*",
            cell,
            re.I,
        ):
            header_like += 1
        elif PERIOD_DATE_HEADER_RE.search(cell):
            header_like += 1
        elif re.fullmatch(r"notes?", cell.strip(), re.I):
            header_like += 1
    return header_like >= max(1, len(cells) // 2)


def _amount_tokens_in_cell(text: str) -> List[str]:
    eu_tokens = [part.strip() for part in _EU_THOUSANDS_AMOUNT_RE.findall(str(text))]
    if eu_tokens:
        return eu_tokens
    parts = re.findall(r"\(\s*-?[\d,]+(?:\.\d+)?\s*\)|-?[\d,]+(?:\.\d+)?", str(text))
    tokens: List[str] = []
    for part in parts:
        digits = re.sub(r"[^\d]", "", part)
        if len(digits) < 4 and "," not in part and "(" not in part:
            continue
        tokens.append(part.strip())
    return tokens


def _years_from_packed_header(df, page_text: str, n_cols: int) -> List[int]:
    sources: List[str] = [str(c) for c in df.columns]
    for row_idx in range(min(4, len(df))):
        for col_idx in range(len(df.columns)):
            sources.append(str(df.iloc[row_idx, col_idx]))
    sources.append(page_text[:800])
    years: List[int] = []
    for src in sources:
        for y in re.findall(r"\b(20\d{2})\b", str(src)):
            yi = int(y)
            if yi not in years:
                years.append(yi)
    years.sort()
    if len(years) >= n_cols:
        return years[-n_cols:]
    return years


def _is_packed_statement_grid(df) -> bool:
    if df is None or df.empty:
        return False
    header_packed = any(
        len(re.findall(r"\b20\d{2}\b", str(col))) >= 3 for col in df.columns
    )
    if not header_packed and len(df.columns) > 3:
        return False
    packed_cell_rows = 0
    for _, row in df.iterrows():
        for val in row.values:
            if len(_amount_tokens_in_cell(str(val))) >= 3:
                packed_cell_rows += 1
                break
    if header_packed and packed_cell_rows >= 2:
        return True
    if len(df.columns) <= 2 and packed_cell_rows >= max(2, len(df) // 6):
        return True
    return False


def _expand_packed_statement_grid(df, page_text: str):
    """pdfplumber 将多列金额压入单格时，展开为常规多列表格。"""
    import pandas as pd

    if not _is_packed_statement_grid(df):
        return df

    label_col = _label_column_index(df)
    max_tokens = 0
    for _, row in df.iterrows():
        row_tokens: List[str] = []
        for col_idx, val in enumerate(row.values):
            if col_idx == label_col:
                continue
            row_tokens.extend(_amount_tokens_in_cell(str(val)))
        max_tokens = max(max_tokens, len(row_tokens))
    if max_tokens < 2:
        return df

    years = _years_from_packed_header(df, page_text, max_tokens)
    period_labels = [str(y) for y in years] if years else [f"col{i}" for i in range(max_tokens)]
    while len(period_labels) < max_tokens:
        period_labels.append(f"extra{len(period_labels)}")
    period_labels = period_labels[:max_tokens]

    new_rows: List[List[str]] = []
    for _, row in df.iterrows():
        label = str(row.iloc[label_col]).strip()
        if not label:
            continue
        if re.fullmatch(r"(?:20\d{2})(?:\s+20\d{2})*", label):
            continue
        if re.search(r"^(?:RMB|USD|notes?)\b", label, re.I):
            continue
        tokens: List[str] = []
        for col_idx, val in enumerate(row.values):
            if col_idx == label_col:
                continue
            tokens.extend(_amount_tokens_in_cell(str(val)))
        if not tokens:
            continue
        if len(tokens) > max_tokens:
            tokens = tokens[-max_tokens:]
        while len(tokens) < max_tokens:
            tokens.append("")
        new_rows.append([label] + tokens)

    if len(new_rows) < 4:
        return df
    return pd.DataFrame(new_rows, columns=["label"] + period_labels)


def _label_column_index(df) -> int:
    """找标签列：通常是第一个非年份、非空的文本列。"""
    for col_idx in range(len(df.columns)):
        sample = " ".join(str(df.iloc[i, col_idx]) for i in range(min(8, len(df))))
        if re.search(r"(20\d{2})", sample) and col_idx > 0 and _column_looks_like_period_header(df, col_idx):
            continue
        text_rows = sum(
            1
            for i in range(min(12, len(df)))
            if str(df.iloc[i, col_idx]).strip() and not re.fullmatch(r"[\d$,.\s()\-]+", str(df.iloc[i, col_idx]).strip())
        )
        if text_rows >= 3:
            return col_idx
    return 0


def _merge_label_and_values(
    row_values: list,
    data_cols: List[int],
    label_col: int = 0,
) -> Tuple[str, List[str]]:
    """把标签列与脚注列合并为行标签；跳过误入标签区的数值单元格。"""
    if not data_cols:
        return "", []
    first_data = min(data_cols)
    label_parts: List[str] = []
    label_text = str(row_values[label_col]).strip()
    if label_text and not _cell_looks_like_amount(label_text):
        label_parts.append(label_text)
    for i in range(label_col + 1, first_data):
        part = str(row_values[i]).strip()
        if part and not _cell_looks_like_amount(part):
            label_parts.append(part)
    label = " ".join(label_parts).strip()
    raw_values = [str(row_values[i]).strip() for i in data_cols]
    return label, raw_values


def _expand_packed_amount_cells(raw_values: List[str]) -> List[str]:
    """拆分同一单元格内并列的多个金额（如 HSBC '23,979  23,533'）。"""
    expanded: List[str] = []
    for raw in raw_values:
        text = str(raw).strip()
        if not text:
            expanded.append(raw)
            continue
        if _EU_THOUSANDS_AMOUNT_RE.fullmatch(text):
            expanded.append(raw)
            continue
        eu_parts = [part.strip() for part in _EU_THOUSANDS_AMOUNT_RE.findall(text)]
        if len(eu_parts) > 1:
            expanded.extend(eu_parts)
            continue
        parts = re.findall(r"\(\s*-?[\d,]+(?:\.\d+)?\s*\)|-?[\d,]+(?:\.\d+)?", text)
        numeric = [p.strip() for p in parts if re.search(r"\d", p)]
        if len(numeric) > 1:
            expanded.extend(numeric)
        else:
            expanded.append(raw)
    return expanded


def build_statement_grid(
    page,
    page_text: str,
    statement_type: str,
    fiscal_calendar: Optional[Dict[int, str]] = None,
    preferred_currency: Optional[str] = None,
) -> Optional[StatementGrid]:
    df = extract_text_grid_from_page(page, min_cols=2, min_rows=4)
    if df is None or df.empty:
        return None
    df = _expand_packed_statement_grid(df, page_text)
    return _dataframe_to_statement_grid(
        df,
        page_text,
        statement_type,
        fiscal_calendar=fiscal_calendar,
        preferred_currency=preferred_currency,
    )


def _dataframe_to_statement_grid(
    df,
    page_text: str,
    statement_type: str,
    fiscal_calendar: Optional[Dict[int, str]] = None,
    preferred_currency: Optional[str] = None,
) -> Optional[StatementGrid]:
    pref = preferred_currency or _preferred_currency_from_text(page_text)
    data_cols, period_ends = _detect_period_columns(df, page_text, fiscal_calendar, pref)
    if len(data_cols) < 2:
        return None

    label_col = _label_column_index(df)
    rows: List[Tuple[str, List[str]]] = []
    pending_label = ""
    section_prefix = ""
    for _, row in df.iterrows():
        label, raw_values = _merge_label_and_values(list(row.values), data_cols, label_col)
        if not label or re.fullmatch(r"(20\d{2})", label):
            continue
        has_amounts = any(_cell_has_amount(v) for v in raw_values)
        if not has_amounts:
            if label and not _cell_looks_like_amount(label):
                if re.search(r"per share", label, re.I):
                    section_prefix = label
                    pending_label = ""
                elif not re.match(r"^and\s+", label, re.I):
                    pending_label = label
            continue

        label, pending_label, section_prefix = _resolve_split_row_label(
            label, pending_label, section_prefix
        )
        raw_values = _expand_packed_amount_cells(raw_values)
        if len(raw_values) > len(period_ends):
            raw_values = raw_values[: len(period_ends)]
        rows.append((label, raw_values))

    if not rows:
        return None

    return StatementGrid(statement_type=statement_type, period_ends=period_ends, rows=rows)


def find_row_values(grid: StatementGrid, field: GlobalField) -> Tuple[str, Dict[str, float]]:
    per_share = field.scale == ValueScale.PER_SHARE
    best_label = ""
    best_score = 0.0
    best_values: Dict[str, float] = {}

    for label, values in grid.rows:
        score = _row_label_score(label, field)
        if score < 0.55:
            continue
        parsed: Dict[str, float] = {}
        for period_end, raw in zip(grid.period_ends, values):
            val = _parse_cell_amount(raw, per_share=per_share)
            if val is not None:
                parsed[period_end] = val

        if not parsed:
            continue
        if (
            field.field_id == "net_income"
            and len(parsed) < max(2, len(grid.period_ends) - 1)
            and "attributable" not in _normalize_label(label)
            and "holding" not in _normalize_label(label)
        ):
            continue
        if field.field_id == "revenue" and all(v <= 0 for v in parsed.values()):
            continue
        if field.field_id in ("revenue", "total_assets", "gross_profit") and all(
            abs(v) < 1000 for v in parsed.values()
        ):
            continue
        if field.field_id == "eps_basic" and all(abs(v) > 500 for v in parsed.values()):
            continue

        tie = score + len(parsed) * 0.01
        if tie > best_score:
            best_score = tie
            best_label = label
            best_values = parsed
        elif tie == best_score and field.field_id == "net_income":
            if "attributable to" in _normalize_label(label) and "attributable to" not in _normalize_label(best_label):
                best_label = label
                best_values = parsed
            elif re.search(r"(?:group\s+)?holding\s+limited$", _normalize_label(label)) and re.fullmatch(
                r"net income(?: \(loss\))?", _normalize_label(best_label)
            ):
                best_label = label
                best_values = parsed
        elif tie == best_score and field.field_id == "revenue":
            if _revenue_label_priority(label) > _revenue_label_priority(best_label):
                best_label = label
                best_values = parsed

    return best_label, best_values


def _revenue_label_priority(label: str) -> int:
    norm = _normalize_label(label)
    if COMPANY_TOTAL_REVENUE_RE.search(norm):
        return 2
    if SEGMENT_TOTAL_REVENUE_RE.search(norm):
        return 1
    return 0


def _cell_needs_text_fallback(raw: str) -> bool:
    text = str(raw).strip()
    if not text:
        return True
    if _dedupe_stuttered_text(text) != text:
        return True
    digits = re.sub(r"[^\d]", "", text)
    if len(digits) >= 8:
        dup_adjacent = sum(1 for i in range(len(digits) - 1) if digits[i] == digits[i + 1])
        if dup_adjacent >= len(digits) * 0.35:
            return True
    if re.search(r",,", text):
        return True
    return False


def _grid_row_raw_values(grid: StatementGrid, label: str) -> List[str]:
    for row_label, values in grid.rows:
        if row_label == label:
            return values
    return []


def _derive_total_liabilities(
    grids: Dict[str, StatementGrid],
    target_periods: List[str],
) -> Tuple[str, Dict[str, float]]:
    """无独立 Total liabilities 行时，先加总流动/非流动负债，再用 assets − equity 推导。"""
    if "balance" not in grids:
        return "", {}
    balance = grids["balance"]
    summed = _sum_liability_components(balance, target_periods)
    assets_field = next(f for f in GLOBAL_FIELDS_V1 if f.field_id == "total_assets")
    equity_field = next(f for f in GLOBAL_FIELDS_V1 if f.field_id == "total_equity")
    _, assets = find_row_values(balance, assets_field)
    _, equity = find_row_values(balance, equity_field)

    derived_from_equation: Dict[str, float] = {}
    if assets and equity:
        for period_end in target_periods:
            a = assets.get(period_end)
            e = equity.get(period_end)
            if a is None or e is None:
                year = period_end[:4]
                for pe, val in assets.items():
                    if pe.startswith(year):
                        a = val
                        break
                for pe, val in equity.items():
                    if pe.startswith(year):
                        e = val
                        break
            if a is not None and e is not None:
                derived_from_equation[period_end] = round(a - e, 2)

    if summed[1] and derived_from_equation:
        for period_end in target_periods:
            component = summed[1].get(period_end)
            equation = derived_from_equation.get(period_end)
            if component is None or equation is None:
                continue
            tolerance = max(1.0, abs(equation) * 0.02)
            if abs(component - equation) > tolerance:
                return "derived: total assets − total equity", derived_from_equation
        return summed

    if summed[1]:
        return summed

    if derived_from_equation:
        return "derived: total assets − total equity", derived_from_equation
    return "", {}


def _sum_liability_components(
    balance: StatementGrid,
    target_periods: List[str],
) -> Tuple[str, Dict[str, float]]:
    current_label = ""
    noncurrent_label = ""
    current_vals: Dict[str, float] = {}
    noncurrent_vals: Dict[str, float] = {}
    for row_label, values in balance.rows:
        norm = _normalize_label(row_label)
        if re.fullmatch(r"total current liabilities", norm):
            current_label = row_label
            current_vals = _parse_row_values(balance, row_label, target_periods)
        elif re.fullmatch(r"total non-current liabilities", norm):
            noncurrent_label = row_label
            noncurrent_vals = _parse_row_values(balance, row_label, target_periods)
    if not current_vals and not noncurrent_vals:
        return "", {}
    derived: Dict[str, float] = {}
    for period_end in target_periods:
        parts = []
        for source in (current_vals, noncurrent_vals):
            val = source.get(period_end)
            if val is None:
                year = period_end[:4]
                for pe, v in source.items():
                    if pe.startswith(year):
                        val = v
                        break
            if val is not None:
                parts.append(val)
        if parts:
            derived[period_end] = round(sum(parts), 2)
    if not derived:
        return "", {}
    label = "derived: total non-current liabilities + total current liabilities"
    return label, derived


def _parse_row_values(
    grid: StatementGrid,
    label: str,
    target_periods: List[str],
) -> Dict[str, float]:
    values = _grid_row_raw_values(grid, label)
    if not values:
        return {}
    parsed: Dict[str, float] = {}
    for idx, period_end in enumerate(grid.period_ends[: len(values)]):
        raw = values[idx]
        if not str(raw).strip():
            continue
        val = _parse_cell_amount(raw)
        if val is not None:
            parsed[period_end] = val
    return {pe: parsed[pe] for pe in target_periods if pe in parsed}


def _derive_total_equity(
    grids: Dict[str, StatementGrid],
    target_periods: List[str],
) -> Tuple[str, Dict[str, float]]:
    """无独立 Total equity 行时，用 assets − liabilities 推导。"""
    if "balance" not in grids:
        return "", {}
    balance = grids["balance"]
    assets_field = next(f for f in GLOBAL_FIELDS_V1 if f.field_id == "total_assets")
    liabilities_field = next(f for f in GLOBAL_FIELDS_V1 if f.field_id == "total_liabilities")
    _, assets = find_row_values(balance, assets_field)
    _, liabilities = find_row_values(balance, liabilities_field)
    if not liabilities:
        label, liabilities = _derive_total_liabilities(grids, target_periods)
        if not liabilities:
            return "", {}
    if not assets:
        return "", {}

    derived: Dict[str, float] = {}
    for period_end in target_periods:
        a = assets.get(period_end)
        l = liabilities.get(period_end)
        if a is None or l is None:
            year = period_end[:4]
            for pe, val in assets.items():
                if pe.startswith(year):
                    a = val
                    break
            for pe, val in liabilities.items():
                if pe.startswith(year):
                    l = val
                    break
        if a is not None and l is not None:
            derived[period_end] = round(a - l, 2)
    return "derived: total assets − total liabilities", derived


def _find_orphan_cash_row(grid: StatementGrid) -> Tuple[str, Dict[str, float]]:
    """PDF 网格首行常丢失「Cash and cash equivalents」标签，仅保留 $ 与金额。"""
    for idx, (label, values) in enumerate(grid.rows[:4]):
        norm = _normalize_label(label)
        if norm not in {"$", "($", ""}:
            continue
        parsed: Dict[str, float] = {}
        for period_end, raw in zip(grid.period_ends, values):
            val = _parse_cell_amount(raw)
            if val is not None:
                parsed[period_end] = val
        if parsed:
            return label or "Cash and cash equivalents", parsed
    return "", {}


class StatementGridExtractor:
    """坐标表格优先的 PDF 财报提取器。"""

    def extract_page_grids(
        self,
        pdf_path: str,
        statement_pages: Dict[str, int],
        pages_text: List[str],
        preferred_currency: Optional[str] = None,
    ) -> Dict[str, StatementGrid]:
        grids: Dict[str, StatementGrid] = {}
        fiscal_calendar = build_fiscal_calendar(pages_text, statement_pages)
        with pdfplumber.open(pdf_path) as pdf:
            for stype, page_num in statement_pages.items():
                start, end = _statement_page_span(pages_text, page_num, stype)
                merged_text = pages_text[page_num]
                if end > start + 1:
                    from backend.markets.us.statement_text import merge_statement_pages

                    merged_text = merge_statement_pages(pages_text, start, stype)

                pref = preferred_currency or _preferred_currency_from_text(merged_text)
                all_rows: List[Tuple[str, List[str]]] = []
                period_ends: List[str] = []
                for pnum in range(start, end):
                    if pnum >= len(pdf.pages):
                        break
                    if not _page_belongs_to_statement(pages_text[pnum], stype):
                        continue
                    page = pdf.pages[pnum]
                    grid = build_statement_grid(
                        page,
                        pages_text[pnum],
                        stype,
                        fiscal_calendar,
                        preferred_currency=pref,
                    )
                    if not grid:
                        continue
                    if not period_ends:
                        period_ends = grid.period_ends
                    for row in grid.rows:
                        if row not in all_rows:
                            all_rows.append(row)
                if all_rows and period_ends:
                    grids[stype] = StatementGrid(
                        statement_type=stype,
                        period_ends=period_ends,
                        rows=all_rows,
                    )
        return grids

    def extract_html_grids(
        self,
        html_path: str,
        statement_pages: Dict[str, int],
        pages_text: List[str],
        preferred_currency: Optional[str] = None,
    ) -> Dict[str, StatementGrid]:
        from backend.markets.us.html_grid_extractor import extract_html_statement_grids

        return extract_html_statement_grids(
            html_path,
            statement_pages,
            pages_text,
            preferred_currency=preferred_currency,
        )

    def extract_fields(
        self,
        grids: Dict[str, StatementGrid],
        target_periods: List[str],
    ) -> Tuple[List[Tuple[str, str, str, float]], List[str]]:
        """返回 [(field_id, period_end, source_label, value), ...], errors。"""
        values: List[Tuple[str, str, str, float]] = []
        errors: List[str] = []
        missing_grids: set[str] = set()

        for field_def in GLOBAL_FIELDS_V1:
            stype = STMT_FIELDS.get(field_def.statement)
            if not stype or stype not in grids:
                if stype:
                    missing_grids.add(stype)
                continue

            label, by_period = find_row_values(grids[stype], field_def)
            if (
                field_def.field_id == "total_liabilities"
                and label
                and (
                    re.search(r"\bcurrent\b", _normalize_label(label))
                    or EQUITY_LIABILITIES_COMBINED_RE.search(_normalize_label(label))
                )
            ):
                label, by_period = "", {}
            if not by_period and field_def.field_id == "total_liabilities":
                label, by_period = _derive_total_liabilities(grids, target_periods)
            if not by_period and field_def.field_id == "total_equity":
                label, by_period = _derive_total_equity(grids, target_periods)
            if not by_period and field_def.field_id == "cash" and stype == "balance":
                label, by_period = _find_orphan_cash_row(grids[stype])
            raw_cells: List[str] = _grid_row_raw_values(grids[stype], label) if label else []
            if (
                by_period
                and raw_cells
                and any(
                    _cell_needs_text_fallback(raw)
                    for raw in raw_cells
                    if str(raw).strip()
                )
            ):
                by_period = {}
            if not by_period:
                continue

            label_score = 1.0 if label.startswith("derived:") else _row_label_score(label, field_def)
            if label_score < 0.85 and field_def.field_id == "total_liabilities":
                derived_label, derived_by_period = _derive_total_liabilities(grids, target_periods)
                if derived_by_period:
                    label, by_period = derived_label, derived_by_period
                    label_score = 1.0
            if label_score < 0.85:
                continue

            for period_end in target_periods:
                val = by_period.get(period_end)
                if val is None:
                    year = period_end[:4]
                    for pe, v in by_period.items():
                        if pe.startswith(year):
                            val = v
                            period_end = pe
                            break
                if val is None:
                    continue
                values.append((field_def.field_id, period_end, label, val))

        for stype in sorted(missing_grids):
                errors.append(f"Missing statement grid: {stype}")

        return values, errors
